version: "3.1"

services: 
    vue_dev:
        build: ./
        image: vue_dev_image
        container_name: vue_dev
        volumes: 
            - ../:/workspace
        ports: 
            - 8080:8080
        command: sleep infinity